language: android
jdk: openjdk8
dist: trusty

env:
  global:
  - ANDROID_API_LEVEL=32
  - EMULATOR_API=22
  - ANDROID_BUILD_TOOLS_VERSION=30.0.3

android:
  licenses:
    - '.*'
 
  components:
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$EMULATOR_API
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-android-$EMULATOR_API
 
before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-$ANDROID_API_LEVEL"
  - yes | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS_VERSION"
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
  - export JAVA_HOME=$HOME/openjdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh -F 11 --target $JAVA_HOME
  - # do stuff with open OpenJDK 11
  - chmod +x gradlew

before_script:
  - echo no | android create avd --force -n test -t android-$EMULATOR_API --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator

script:
  - ./gradlew clean build
  - ./gradlew test
  - ./gradlew build check
