language: android
dist: trusty
sudo: required
jdk: openjdk11

env:
  global:
  - ANDROID_API_LEVEL=32
  - ANDROID_BUILD_TOOLS_VERSION=30.0.2
  
before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-32"
  - yes | sdkmanager "build-tools;30.0.2"
  
android:
  components:
    - tools
    - platform-tools
  licenses:
    - '.*'

before_script:
  - chmod +x gradlew 
  
script:
  - ./gradlew clean build
  - ./gradlew test
