language: android
dist: trusty
jdk: openjdk11
before_install:
  - yes | sdkmanager "platforms;android-32"
android:
  components:
    - android-23
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - '.*'
