language: android
jdk: openjdk11
dist: trusty

env:
  global:
  - ANDROID_API_LEVEL=32
  - EMULATOR_API=23
  - ANDROID_BUILD_TOOLS_VERSION=30.0.2

android:
  licenses:
    - '.*'
 
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$EMULATOR_API
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-android-$EMULATOR_API
 
before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-$ANDROID_API_LEVEL"
  - yes | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS_VERSION"

before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator

script:
  - ./gradlew clean build
  - ./gradlew test
  - ./gradlew build check
